services:
  - type: web
    name: tamonly
    runtime: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: Tamonly
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://tamilonlymv.onrender.com
      - key: LOG_CHANNEL
        value: stderr
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: tw-fastwitterx.e.aivencloud.com
      - key: DB_PORT
        value: "19300"
      - key: DB_DATABASE
        value: Tamilonly
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_PASSWORD
        sync: false
      - key: MYSQL_ATTR_SSL_VERIFY_SERVER_CERT
        value: "false"
      - key: RUN_MIGRATIONS
        value: "true"
      - key: RUN_SEEDER
        value: "false"
